/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.Poruka;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import konstante.Operacije;
import kontroler.Komunikacija;
import modeli.ModelTabelePoruke;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author frado
 */
public class KlijentskaForma extends javax.swing.JFrame {
    
    Korisnik ulogovani;

    

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(Korisnik ulogovani) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Klijentska forma");
        Komunikacija.getInstance().setKf(this);
        txt_korisnik.setEditable(false);
        txt_korisnik.setText("Izaberi korisnika iz liste ulogovanih");
        this.ulogovani = ulogovani;
        tbl_poslednjeTriPoruke.setModel(new ModelTabelePoruke());
        ModelTabelePoruke model = new ModelTabelePoruke(ulogovani);
        Thread thread = new Thread(model);
        thread.start();
        tbl_poruke.setModel(model);
        lbl_ulogovani.setText("Ulogovani korisnik: " + ulogovani.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ulogovani = new javax.swing.JLabel();
        btn_odjava = new javax.swing.JButton();
        btn_prikaziUlogovane = new javax.swing.JButton();
        txt_korisnik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_poruka = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_posaljiSvima = new javax.swing.JButton();
        btn_posaljiIzabranom = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_poslednjeTriPoruke = new javax.swing.JTable();
        btn_prikaziPoruku = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_poruke = new javax.swing.JTable();
        btn_prikaziPoruku1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_ulogovani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ulogovani.setText("Ulogovani");

        btn_odjava.setText("Odjavi se");

        btn_prikaziUlogovane.setText("Prikazi sve ulogovane korisnike");
        btn_prikaziUlogovane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prikaziUlogovaneActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisnik kome saljes poruku:");

        txt_poruka.setColumns(20);
        txt_poruka.setRows(5);
        txt_poruka.setText("Cao!");
        jScrollPane1.setViewportView(txt_poruka);

        jLabel2.setText("Poruka:");

        btn_posaljiSvima.setText("Posalji poruku svima");
        btn_posaljiSvima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posaljiSvimaActionPerformed(evt);
            }
        });

        btn_posaljiIzabranom.setText("Posalji poruku izabranom korisniku");
        btn_posaljiIzabranom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posaljiIzabranomActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Poslednje 3 poruke"));

        tbl_poslednjeTriPoruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_poslednjeTriPoruke);

        btn_prikaziPoruku.setText("Prikazi celu poruku");
        btn_prikaziPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prikaziPorukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(btn_prikaziPoruku, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btn_prikaziPoruku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Poruke za tebe"));

        tbl_poruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_poruke);

        btn_prikaziPoruku1.setText("Prikazi celu poruku");
        btn_prikaziPoruku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prikaziPoruku1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(btn_prikaziPoruku1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_prikaziPoruku1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_korisnik)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_posaljiSvima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_posaljiIzabranom))
                            .addComponent(btn_prikaziUlogovane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ulogovani)
                        .addGap(412, 412, 412)))
                .addComponent(btn_odjava, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_odjava)
                        .addComponent(lbl_ulogovani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_prikaziUlogovane, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_korisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_posaljiIzabranom, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btn_posaljiSvima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prikaziUlogovaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prikaziUlogovaneActionPerformed
        new FormaUlogovaniKorisnici(this, true).setVisible(true);
    }//GEN-LAST:event_btn_prikaziUlogovaneActionPerformed

    private void btn_posaljiIzabranomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posaljiIzabranomActionPerformed
        
        String poruka = txt_poruka.getText();
        String usernamePrimaoca = txt_korisnik.getText();
        
        if ("Izaberi korisnika iz liste ulogovanih".equals(usernamePrimaoca)) {
            JOptionPane.showMessageDialog(this, "Morate izabrati korisnika kome saljete poruku!");
            return;
        }
        Poruka p = new Poruka(-1, ulogovani.getUsername(), usernamePrimaoca, new Date(), poruka);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacije(Operacije.SACUVAJ_PORUKU);
        kz.setParametar(p);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        
        boolean uspesno = (boolean) so.getOdgovor();
        
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Poruka je uspesno poslata!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom slanja poruke!");
        }
        
    }//GEN-LAST:event_btn_posaljiIzabranomActionPerformed

    private void btn_posaljiSvimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posaljiSvimaActionPerformed
        
        String poruka = txt_poruka.getText();
        
        Poruka p = new Poruka(-1, ulogovani.getUsername(), "Svi", new Date(), poruka);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacije(Operacije.SACUVAJ_PORUKU);
        kz.setParametar(p);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        
        boolean uspesno = (boolean) so.getOdgovor();
        
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Poruka je uspesno poslata!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom slanja poruke!");
        }
        
    }//GEN-LAST:event_btn_posaljiSvimaActionPerformed

    private void btn_prikaziPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prikaziPorukuActionPerformed
        
        int row = tbl_poslednjeTriPoruke.getSelectedRow();
        
        if (row != -1) {
            ModelTabelePoruke mt = (ModelTabelePoruke) tbl_poslednjeTriPoruke.getModel();
            String poruka = mt.vratiPoruku(row);
            
            FormaPoruka fp = new FormaPoruka(this, true, poruka);
            fp.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btn_prikaziPorukuActionPerformed

    private void btn_prikaziPoruku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prikaziPoruku1ActionPerformed
        
        int row = tbl_poruke.getSelectedRow();
        
        if (row != -1) {
            ModelTabelePoruke mt = (ModelTabelePoruke) tbl_poruke.getModel();
            String poruka = mt.vratiPoruku(row);
            
            FormaPoruka fp = new FormaPoruka(this, true, poruka);
            fp.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_prikaziPoruku1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_odjava;
    private javax.swing.JButton btn_posaljiIzabranom;
    private javax.swing.JButton btn_posaljiSvima;
    private javax.swing.JButton btn_prikaziPoruku;
    private javax.swing.JButton btn_prikaziPoruku1;
    private javax.swing.JButton btn_prikaziUlogovane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_ulogovani;
    private javax.swing.JTable tbl_poruke;
    private javax.swing.JTable tbl_poslednjeTriPoruke;
    private javax.swing.JTextField txt_korisnik;
    private javax.swing.JTextArea txt_poruka;
    // End of variables declaration//GEN-END:variables

    public void setujPoslednjeTri(ArrayList<Poruka> poslednjeTri) {
        ModelTabelePoruke mt = (ModelTabelePoruke) tbl_poslednjeTriPoruke.getModel();
        mt.dodajPoslednjeTri(poslednjeTri);
    }

    void setujKorisnika(Korisnik k) {
        txt_korisnik.setText(k.getUsername());
    }
}
